### ISSUE TITLE
Comments: Create an IAM User

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#13]
Link to chapter - http://serverless-stack.com/chapters/create-an-iam-user.html

**Comment by SherpaPsy** [comment]
I wonder if there is a way to reduce the security exposure this creates. I think I might try using roles - since I plan to do the the cli work from a small EC2 instance I can start and stop as required. Will let you know how that goes :)

**Comment by fwang** [comment]
@SherpaPsy That is a great security practice! It is a bit out of the scope of this tutorial, but it is definitely the preferred approach.

For those who are interested, this is around limiting the use of IAM users in favor of IAM roles. The problem with IAM users is that the credentials (`Access key ID` and `Secret access key`) that are assigned and used in AWS CLI are not automatically cycled. By leveraging IAM roles, you can assign temporary short lived credentials to a specific AWS resource, in this case an EC2 instance. When an EC2 instance is launched, you can assign an IAM role, so that when functions or commands run within that instance, they will be executed using the credentials of the IAM role. In this case, IAM services will automatically cycle the credentials that are allocated to the EC2 instance at regular interval.

Actually, our Lambda functions are assigned with IAM roles in the exact same fashion behind the scene with policies allowing it to access DynamoDB.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-an-iam-user/92
